title: Masoud Faramarzi # your name (or website title) here
logo: "/images/photo_2019-12-01_19-04-53.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student- Data Science and Machine Learning Engineering
  <br><br>
  University of Rhode Island
  <br><br>
  <a href="https://www.linkedin.com/in/masoud-faramarzi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
